import json
import random

def load_summaries(file_path="summaries.json"):
    """Load summaries generated by ai_summarization_agent."""
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_social_post(article):
    """
    Format one article summary into a post-ready caption.
    Structure:
      - Hook line
      - Summary snippet
      - Hashtags
      - Call-to-action + link
    """

    hooks = [
        "🚀 Big news in drone tech:",
        "🌍 Game-changing innovation spotted:",
        "⚡ Disruption alert in UAV space:",
        "📰 Latest update you should know:",
    ]
    hook = random.choice(hooks)

    # Shorten summary for social media (keep it concise)
    summary_snippet = (
        article["summary"][:220] + "..."
        if len(article["summary"]) > 220
        else article["summary"]
    )

    hashtags = " ".join(article.get("hashtags", []))

    caption = (
        f"{hook}\n\n"
        f"{summary_snippet}\n\n"
        f"{hashtags}\n\n"
        f"👉 Read more: {article['link']}"
    )

    return {
        "title": article["title"],
        "publishedAt": article.get("publishedAt"),
        "link": article["link"],
        "caption": caption,
        "image": article.get("image") or "https://images.unsplash.com/photo-1487304655522-c039cc299c9d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }


def generate_posts():
    """Generate social posts from summaries.json."""
    articles = load_summaries()
    posts = [generate_social_post(article) for article in articles]

    # Save for later use
    with open("social_posts.json", "w", encoding="utf-8") as f:
        json.dump(posts, f, indent=2, ensure_ascii=False)

    return posts


results = generate_posts()
for post in results:
    print("\n" + "-" * 50)
    print("Title:", post["title"])
    print("Published:", post.get("publishedAt"))
    print("Link:", post["link"])
    print("Caption:\n", post["caption"])
    print("\nImage URL:", post["image"])
